services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
